import Head from 'next/head'
import Image from 'next/image'
import { Form } from 'react-bootstrap'
// import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="container header">
        <h1> Gerador de prescrição </h1>
      </div>
      <Form>
        <Form.Group>
          <Form.Label to="name"> Nome completo </Form.Label>
          <Form.Control type="text" name="name" id="name" placeHolder="Escreva seu nome completo" min="6" required />
          <Form.Label to="copies"> Número de cópias </Form.Label>
          <Form.Control type="number" name="copies" id="copies" />
        </Form.Group>
      </Form>
    </>
  )
}
